name: Run verification checks

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run checks
      run: |
        ./scripts/verify_all.sh

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: docs/data/output/*.json
        commit_message: Comitting verification results
